import { useState } from "react";

export default function Question10(props) {
  const [index, setIndex] = useState(0);

  const onClickSelect = (number) => {
    setIndex(number);
  };
  return (
    <div
      style={{
        alignSelf: "stretch",
        //height: 436,
        flexDirection: "column",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        gap: 32,
        display: "flex",
      }}
    >
      <div
        style={{
          alignSelf: "stretch",
          color: "#0F0E0E",
          fontSize: 24,
          fontFamily: "Inter",
          fontWeight: "500",
          lineHeight: 1,
          wordWrap: "break-word",
          marginTop: 30,
        }}
      >
        How do you evaluate the cybersecurity risk in OT environments?
      </div>
      <div
        style={{
          alignSelf: "stretch",
          // height: 368,
          flexDirection: "column",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          gap: 16,
          display: "flex",
        }}
      >
        <div
          className={index == 1 ? "answerselect" : "answer"}
          onClick={() => onClickSelect(1)}
        >
          <div
            style={{
              flex: "1 1 0",
              fontSize: 16,
              fontFamily: "Inter",
              fontWeight: "400",
              lineHeight: 1,
              wordWrap: "break-word",
            }}
          >
            We do not perform any cybersecurity risk assessment.
          </div>
        </div>
        <div
          className={index == 2 ? "answerselect" : "answer"}
          onClick={() => onClickSelect(2)}
        >
          <div
            style={{
              flex: "1 1 0",
              fontSize: 16,
              fontFamily: "Inter",
              fontWeight: "400",
              lineHeight: 1,
              wordWrap: "break-word",
            }}
          >
            We evaluate Cybersecurity Risks using empiricism based on what
            happened in the last few months and generate a report based on that.
          </div>
        </div>
        <div
          className={index == 3 ? "answerselect" : "answer"}
          onClick={() => onClickSelect(3)}
        >
          <div
            style={{
              flex: "1 1 0",
              fontSize: 16,
              fontFamily: "Inter",
              fontWeight: "400",
              lineHeight: 1,
              wordWrap: "break-word",
            }}
          >
            We established a Cybersecurity Risk Methodology and run it manually
            when needed.
          </div>
        </div>
        <div
          className={index == 4 ? "answerselect" : "answer"}
          onClick={() => onClickSelect(4)}
        >
          <div
            style={{
              flex: "1 1 0",
              fontSize: 16,
              fontFamily: "Inter",
              fontWeight: "400",
              lineHeight: 1,
              wordWrap: "break-word",
            }}
          >
            We established a Cybersecurity Risk Methodology and run a manual
            cybersecurity assessment yearly, then compare the results to the
            previous year to identify pain points and how to invest.
          </div>
        </div>
        <div
          className={index == 5 ? "answerselect" : "answer"}
          onClick={() => onClickSelect(5)}
        >
          <div
            style={{
              flex: "1 1 0",
              fontSize: 16,
              fontFamily: "Inter",
              fontWeight: "400",
              lineHeight: 1,
              wordWrap: "break-word",
            }}
          >
            We established a Cybersecurity Risk Methodology and the main risks
            are identified at the beginning of the year. Then monitored on a
            regular basis using quantitative information generated by our SIEM.
          </div>
        </div>
        <div
          className={index == 6 ? "answerselect" : "answer"}
          onClick={() => onClickSelect(6)}
        >
          <div
            style={{
              flex: "1 1 0",
              fontSize: 16,
              fontFamily: "Inter",
              fontWeight: "400",
              lineHeight: 1,
              wordWrap: "break-word",
            }}
          >
            We established a Cybersecurity Risk Methodology and the main risks
            are identified at the beginning of the year. Then monitored on a
            regular basis using quantitative information generated by our SIEM.
            The cybersecurity risk KPIs are integrated with the Corporative Risk
            KPIs, and monitored by higher company executives.
          </div>
        </div>
      </div>
    </div>
  );
}
